export const ICON_ASSETS = [
  { id: "aulia_icon_01", label: "アウリア", path: "assets/icons/characters/aulia_icon_01.webp" },
  { id: "axion_icon_01", label: "アクシオン", path: "assets/icons/characters/axion_icon_01.webp" },
  { id: "amaryllis_icon_01", label: "アマリリス", path: "assets/icons/characters/amaryllis_icon_01.webp" },
  { id: "amezis_icon_01", label: "アメジス", path: "assets/icons/characters/amezis_icon_01.webp" },
  { id: "ameri_icon_01", label: "アメリ", path: "assets/icons/characters/ameri_icon_01.webp" },
  { id: "ignifa_icon_01", label: "イグニファ", path: "assets/icons/characters/ignifa_icon_01.webp" },
  { id: "elysia_icon_01", label: "エリシア", path: "assets/icons/characters/elysia_icon_01.webp" },
  { id: "elena_icon_01", label: "エレナ", path: "assets/icons/characters/elena_icon_01.webp" },
  { id: "ordina_icon_01", label: "オルディナ", path: "assets/icons/characters/ordina_icon_01.webp" },
  { id: "kagetsu_icon_01", label: "カゲツ", path: "assets/icons/characters/kagetsu_icon_01.webp" },
  { id: "karien_icon_01", label: "カリエン", path: "assets/icons/characters/karien_icon_01.webp" },
  { id: "karin_icon_01", label: "カリン", path: "assets/icons/characters/karin_icon_01.webp" },
  { id: "kelvas_icon_01", label: "ケルヴァス", path: "assets/icons/characters/kelvas_icon_01.webp" },
  { id: "sakuya_orochi_icon_01", label: "サクヤオロチ", path: "assets/icons/characters/sakuya_orochi_icon_01.webp" },
  { id: "shien_icon_01", label: "シエン", path: "assets/icons/characters/shien_icon_01.webp" },
  { id: "sena_icon_01", label: "セナ", path: "assets/icons/characters/sena_icon_01.webp" },
  { id: "soria_icon_01", label: "ソリア", path: "assets/icons/characters/soria_icon_01.webp" },
  { id: "solius_icon_01", label: "ソリウス", path: "assets/icons/characters/solius_icon_01.webp" },
  { id: "soleil_icon_01", label: "ソレーユ", path: "assets/icons/characters/soleil_icon_01.webp" },
  { id: "tsukihane_icon_01", label: "ツキハネ", path: "assets/icons/characters/tsukihane_icon_01.webp" },
  { id: "tsukuyo_icon_01", label: "ツクヨ", path: "assets/icons/characters/tsukuyo_icon_01.webp" },
  { id: "frigia_icon_01", label: "フリギア", path: "assets/icons/characters/frigia_icon_01.webp" },
  { id: "mikage_icon_01", label: "ミカゲ", path: "assets/icons/characters/mikage_icon_01.webp" },
  { id: "mistros_icon_01", label: "ミストロス", path: "assets/icons/characters/mistros_icon_01.webp" },
  { id: "mona_icon_01", label: "モナ", path: "assets/icons/characters/mona_icon_01.webp" },
  { id: "rao_icon_01", label: "ラオ", path: "assets/icons/characters/rao_icon_01.webp" },
  { id: "rafal_icon_01", label: "ラファル", path: "assets/icons/characters/rafal_icon_01.webp" },
  { id: "riva_icon_01", label: "リーヴァ", path: "assets/icons/characters/riva_icon_01.webp" },
  { id: "luxhaul_icon_01", label: "ルクスハウル", path: "assets/icons/characters/luxhaul_icon_01.webp" },
  { id: "lumiana_icon_01", label: "ルミアナ", path: "assets/icons/characters/lumiana_icon_01.webp" },
  { id: "ruga_icon_01", label: "ルーガ", path: "assets/icons/characters/ruga_icon_01.webp" },
  { id: "renaris_icon_01", label: "レナリス", path: "assets/icons/characters/renaris_icon_01.webp" },
  { id: "logos_icon_01", label: "ロゴス", path: "assets/icons/characters/logos_icon_01.webp" }
];

export const ICON_MAP = Object.fromEntries(ICON_ASSETS.map((asset) => [asset.id, asset.path]));
